#include "pattern.h"

// text saying 'hello' with a rainbow

#define WIDTH 21
#define HEIGHT 6

DEFINE_PATTERN {
    { RED, WHITE, RED, WHITE, RED, WHITE, WHITE, WHITE, RED, WHITE, RED, RED, RED, WHITE, RED, RED, RED, WHITE, WHITE, WHITE, RED },
    { ORANGE, WHITE, ORANGE, WHITE, ORANGE, WHITE, ORANGE, ORANGE, ORANGE, WHITE, ORANGE, ORANGE, ORANGE, WHITE, ORANGE, ORANGE, ORANGE, WHITE, ORANGE, WHITE, ORANGE },
    { YELLOW, WHITE, WHITE, WHITE, YELLOW, WHITE, WHITE, YELLOW, YELLOW, WHITE, YELLOW, YELLOW, YELLOW, WHITE, YELLOW, YELLOW, YELLOW, WHITE, YELLOW, WHITE, YELLOW },
    { GREEN, WHITE, GREEN, WHITE, GREEN, WHITE, GREEN, GREEN, GREEN, WHITE, GREEN, GREEN, GREEN, WHITE, GREEN, GREEN, GREEN, WHITE, GREEN, WHITE, GREEN },
    { BLUE, WHITE, BLUE, WHITE, BLUE, WHITE, BLUE, BLUE, BLUE, WHITE, BLUE, BLUE, BLUE, WHITE, BLUE, BLUE, BLUE, WHITE, BLUE, WHITE, BLUE },
    { PURPLE, WHITE, PURPLE, WHITE, PURPLE, WHITE, WHITE, WHITE, PURPLE, WHITE, WHITE, WHITE, PURPLE, WHITE, WHITE, WHITE, PURPLE, WHITE, WHITE, WHITE, PURPLE },
};